swagger: '2.0'
info:
    description: This is a server hosting all apis for Zanmi Learning app
    version: 1.0.0
    title: Zanmi Learning API Store
    contact:
        email: zanmilearning@gmail.com
    license:
        name: Apache 2.0
        url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: zanmilearn.herokuapp.com
basePath: /api/v2
tags:
    - 
        name: Courses
        description: Course Apis
    - 
        name: Topics
        description: Topic Apis
    - 
        name: Contents
        description: Content Apis
    - 
        name: Users
        description: User Apis
schemes:
    - http
    - https
consumes:
    - application/json
produces:
    - application/json
    - text/plain
paths:
    /courses:
        x-swagger-router-controller: courses
        get:
            tags:
                - Courses
            description: Get all Courses
            operationId: getAllCourses
            responses:
                '200':
                    description: Success
                    schema:
                        $ref: '#/definitions/getAllCoursesResponse'
                default:
                    description: Error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
        post:
            tags:
                - Courses
            description: Create a new Course
            operationId: createCourse
            parameters:
                - 
                    name: payload
                    in: body
                    description: course object
                    schema:
                        $ref: '#/definitions/inBody'
            responses:
                '200':
                    description: Success
                    schema:
                        $ref: '#/definitions/getAllCoursesResponse'
                default:
                    description: Error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
        delete:
            tags:
                - Courses
            description: Delete a  Course
            operationId: deleteCourse
            parameters:
                - 
                    name: payload
                    in: body
                    description: course object
                    schema:
                        $ref: '#/definitions/inBody'
            responses:
                '200':
                    description: Success
                    schema:
                        $ref: '#/definitions/getAllCoursesResponse'
                default:
                    description: Error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
    /topics:
        x-swagger-router-controller: topics
        get:
            tags:
                - Topics
            description: Get all Topic
            operationId: getAllTopics
            responses:
                '200':
                    description: Success
                    schema:
                        $ref: '#/definitions/getAllTopicsResponse'
                default:
                    description: Error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
        post:
            tags:
                - Topics
            description: Create a new Topic
            operationId: createTopic
            parameters:
                - 
                    name: payload
                    in: body
                    description: topic object
                    schema:
                        $ref: '#/definitions/inBody'
            responses:
                '200':
                    description: Success
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                default:
                    description: Error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
        delete:
            tags:
                - Courses
            description: Delete a  Course
            operationId: deleteTopic
            parameters:
                - 
                    name: payload
                    in: body
                    description: topic object
                    schema:
                        $ref: '#/definitions/inBody'
            responses:
                '200':
                    description: Success
                    schema:
                        $ref: '#/definitions/getAllTopicsResponse'
                default:
                    description: Error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
    /contents:
        x-swagger-router-controller: contents
        get:
            tags:
                - Contents
            description: Get all Contents
            operationId: getAllContents
            responses:
                '200':
                    description: Success
                    schema:
                        $ref: '#/definitions/getAllContentsResponse'
                default:
                    description: Error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
        post:
            tags:
                - Contents
            description: Create a new Content
            operationId: createContent
            parameters:
                - 
                    name: payload
                    in: body
                    description: content object
                    schema:
                        $ref: '#/definitions/inBody'
            responses:
                '200':
                    description: Success
                    schema:
                        $ref: '#/definitions/inBody'
                default:
                    description: Error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
        delete:
            tags:
                - Contents
            description: Delete a  Content
            operationId: deleteContent
            parameters:
                - 
                    name: payload
                    in: body
                    description: content object
                    schema:
                        $ref: '#/definitions/inBody'
            responses:
                '200':
                    description: Success
                    schema:
                        $ref: '#/definitions/getAllContentsResponse'
                default:
                    description: Error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
    /users:
        x-swagger-router-controller: users
        get:
            tags:
                - Users
            description: Get all Users
            operationId: getAllUsers
            responses:
                '200':
                    description: Success
                    schema:
                        $ref: '#/definitions/getAllUsersResponse'
                default:
                    description: Error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
        post:
            tags:
                - Users
            description: Create a new user/register
            operationId: createUser
            parameters:
                - 
                    name: payload
                    in: body
                    description: user object
                    schema:
                        $ref: '#/definitions/getAllUsersResponse'
            responses:
                '200':
                    description: Success
                    schema:
                        $ref: '#/definitions/getAllUsersResponse'
                default:
                    description: Error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
    /users/validateemail:
        x-swagger-router-controller: users
        get:
            tags:
                - Users
            description: validate email and redirect to app
            operationId: validateEmail
            parameters:
                - 
                    name: username
                    in: query
                    description: username
                    type: string
                - 
                    name: hash
                    in: query
                    description: hash
                    type: string
            responses:
                '302':
                    description: redirect after successfull verification
                    headers:
                        Location:
                            type: string
                default:
                    description: Error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
    '/users/getUserByUserName/{username}':
        x-swagger-router-controller: users
        get:
            tags:
                - Users
            description: get user by user name
            operationId: getUserByUserName
            parameters:
                - 
                    name: username
                    in: path
                    description: username
                    type: string
                    required: true
            responses:
                '200':
                    description: Success
                    schema:
                        $ref: '#/definitions/getAllUsersResponse'
                default:
                    description: Error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
    /swagger:
        x-swagger-pipe: swagger_raw
definitions:
    HelloWorldResponse:
        required:
            - message
        properties:
            message:
                type: string
    getAllCoursesResponse:
        required:
            - courseName
            - courseDesc
            - courseNodeId
        properties:
            courseName:
                type: string
            courseDesc:
                type: string
            courseType:
                type: string
            courseNodeId:
                type: number
            courseFont:
                type: string
            topics:
                type: array
                items:
                    type: string
    getAllTopicsResponse:
        required:
            - topicName
            - topicDesc
            - topicNodeId
        properties:
            topicName:
                type: string
            topicDesc:
                type: string
            topicNodeId:
                type: number
            topicFont:
                type: string
            contents:
                type: array
                items:
                    type: object
            parentNodeId:
                type: number
    getAllContentsResponse:
        required:
            - contentName
            - contentDesc
            - contentNodeId
        properties:
            contentName:
                type: string
            contentDesc:
                type: string
            contentNodeId:
                type: number
    getAllUsersResponse:
        required:
            - username
            - password
            - email
        properties:
            username:
                type: string
            password:
                type: string
            email:
                type: string
            location:
                type: string
            active:
                type: boolean
            verified:
                type: boolean
            created_at:
                type: string
            updated_at:
                type: string
    usernameParamResponse:
        required:
            - username
        properties:
            username:
                type: string
    inBody:
        type: object
    ErrorResponse:
        required:
            - message
        properties:
            message:
                type: string
