swagger: '2.0'
info:
    description: This is a server hosting all apis for Zanmi Learning app
    version: 1.0.0
    title: Zanmi Learning API Store
    contact:
        email: zanmilearning@gmail.com
    license:
        name: Apache 2.0
        url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:10010'
basePath: /v2
tags:
    - 
        name: Courses
        description: Course Apis
    - 
        name: Topics
        description: Topics Apis
schemes:
    - http
    - https
consumes:
    - application/json
produces:
    - application/json
paths:
    /courses:
        x-swagger-router-controller: courses
        get:
            tags:
                - courses
            description: Get all Courses
            operationId: getAllCourses
            responses:
                '200':
                    description: Success
                    schema:
                        $ref: '#/definitions/getAllCoursesResponse'
                default:
                    description: Error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
        post:
            tags:
                - courses
            description: Create a new Course
            operationId: createCourse
            parameters:
                - 
                    name: course
                    in: body
                    description: course object
                    schema:
                        $ref: '#/definitions/getAllCoursesResponse'
            responses:
                '200':
                    description: Success
                    schema:
                        $ref: '#/definitions/getAllCoursesResponse'
                default:
                    description: Error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
    /swagger:
        x-swagger-pipe: swagger_raw
definitions:
    HelloWorldResponse:
        required:
            - message
        properties:
            message:
                type: string
    getAllCoursesResponse:
        required:
            - courseName
            - courseDesc
        properties:
            courseName:
                type: string
            courseDesc:
                type: string
            courseType:
                type: string
    ErrorResponse:
        required:
            - message
        properties:
            message:
                type: string
